services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/data
      - ./backups:/backups
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    command: server /data

volumes:
  minio-data:
