services:
  api:
    build: ../..
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - minio
    environment:
      - MONGO_URI=mongodb://mongodb:27017/db
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=youraccesskey
      - MINIO_SECRET_KEY=yoursecretkey
